// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// APIErrorType - api_error
type APIErrorType string

const (
	APIErrorTypeAPIError APIErrorType = "api_error"
)

func (e APIErrorType) ToPointer() *APIErrorType {
	return &e
}

func (e *APIErrorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api_error":
		*e = APIErrorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for APIErrorType: %v", v)
	}
}

type APIError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// api_error
	Type *APIErrorType `json:"type,omitempty"`
}

var _ error = &APIError{}

func (e *APIError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
