// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// AuthenticationErrorType - authentication_error
type AuthenticationErrorType string

const (
	AuthenticationErrorTypeAuthenticationError AuthenticationErrorType = "authentication_error"
)

func (e AuthenticationErrorType) ToPointer() *AuthenticationErrorType {
	return &e
}

func (e *AuthenticationErrorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "authentication_error":
		*e = AuthenticationErrorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuthenticationErrorType: %v", v)
	}
}

type AuthenticationError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// authentication_error
	Type *AuthenticationErrorType `json:"type,omitempty"`
}

var _ error = &AuthenticationError{}

func (e *AuthenticationError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
