// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// SchemasType - authentication_error
type SchemasType string

const (
	SchemasTypeAuthenticationError SchemasType = "authentication_error"
)

func (e SchemasType) ToPointer() *SchemasType {
	return &e
}

func (e *SchemasType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "authentication_error":
		*e = SchemasType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasType: %v", v)
	}
}

type AuthenticationError struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// authentication_error
	Type *SchemasType `json:"type,omitempty"`
}

var _ error = &AuthenticationError{}

func (e *AuthenticationError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
