// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// APIErrorType - api_error
type APIErrorType string

const (
	APIErrorTypeAPIError APIErrorType = "api_error"
)

func (e APIErrorType) ToPointer() *APIErrorType {
	return &e
}

func (e *APIErrorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api_error":
		*e = APIErrorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for APIErrorType: %v", v)
	}
}
