// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AuthenticationErrorType - authentication_error
type AuthenticationErrorType string

const (
	AuthenticationErrorTypeAuthenticationError AuthenticationErrorType = "authentication_error"
)

func (e AuthenticationErrorType) ToPointer() *AuthenticationErrorType {
	return &e
}

func (e *AuthenticationErrorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "authentication_error":
		*e = AuthenticationErrorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuthenticationErrorType: %v", v)
	}
}
