// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateOrderBackendRequest struct {
	// The customer details that are necessary. Note that you can pass dummy details if your use case does not require the customer details.
	CustomerDetails CustomerDetails `json:"customer_details"`
	// Bill amount for the order. Provide upto two decimals. 10.15 means Rs 10 and 15 paisa
	OrderAmount float64 `json:"order_amount"`
	// Currency for the order. INR if left empty. Contact care@cashfree.com to enable new currencies.
	OrderCurrency string `json:"order_currency"`
	// Time after which the order expires. Customers will not be able to make the payment beyond the time specified here. We store timestamps in IST, but you can provide them in a valid ISO 8601 time format.
	OrderExpiryTime *string `json:"order_expiry_time,omitempty"`
	// Order identifier present in your system. Alphanumeric and only - and _ allowed.
	OrderID   *string    `json:"order_id,omitempty"`
	OrderMeta *OrderMeta `json:"order_meta,omitempty"`
	// Order note for reference.
	OrderNote   *string       `json:"order_note,omitempty"`
	OrderSplits []VendorSplit `json:"order_splits,omitempty"`
	// Custom Tags which can be passed for an order. A maximum of 6 tags can be added
	OrderTags map[string]string `json:"order_tags,omitempty"`
	Terminal  *TerminalDetails  `json:"terminal,omitempty"`
}

func (o *CreateOrderBackendRequest) GetCustomerDetails() CustomerDetails {
	if o == nil {
		return CustomerDetails{}
	}
	return o.CustomerDetails
}

func (o *CreateOrderBackendRequest) GetOrderAmount() float64 {
	if o == nil {
		return 0.0
	}
	return o.OrderAmount
}

func (o *CreateOrderBackendRequest) GetOrderCurrency() string {
	if o == nil {
		return ""
	}
	return o.OrderCurrency
}

func (o *CreateOrderBackendRequest) GetOrderExpiryTime() *string {
	if o == nil {
		return nil
	}
	return o.OrderExpiryTime
}

func (o *CreateOrderBackendRequest) GetOrderID() *string {
	if o == nil {
		return nil
	}
	return o.OrderID
}

func (o *CreateOrderBackendRequest) GetOrderMeta() *OrderMeta {
	if o == nil {
		return nil
	}
	return o.OrderMeta
}

func (o *CreateOrderBackendRequest) GetOrderNote() *string {
	if o == nil {
		return nil
	}
	return o.OrderNote
}

func (o *CreateOrderBackendRequest) GetOrderSplits() []VendorSplit {
	if o == nil {
		return nil
	}
	return o.OrderSplits
}

func (o *CreateOrderBackendRequest) GetOrderTags() map[string]string {
	if o == nil {
		return nil
	}
	return o.OrderTags
}

func (o *CreateOrderBackendRequest) GetTerminal() *TerminalDetails {
	if o == nil {
		return nil
	}
	return o.Terminal
}
