// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ErrorResponseType - One of ["invalid_request_error", "authentication_error", "rate_limit_error", "validation_error", "api_error"]
type ErrorResponseType string

const (
	ErrorResponseTypeInvalidRequestError ErrorResponseType = "invalid_request_error"
	ErrorResponseTypeAuthenticationError ErrorResponseType = "authentication_error"
	ErrorResponseTypeRateLimitError      ErrorResponseType = "rate_limit_error"
	ErrorResponseTypeValidationError     ErrorResponseType = "validation_error"
	ErrorResponseTypeAPIError            ErrorResponseType = "api_error"
)

func (e ErrorResponseType) ToPointer() *ErrorResponseType {
	return &e
}

func (e *ErrorResponseType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "invalid_request_error":
		fallthrough
	case "authentication_error":
		fallthrough
	case "rate_limit_error":
		fallthrough
	case "validation_error":
		fallthrough
	case "api_error":
		*e = ErrorResponseType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrorResponseType: %v", v)
	}
}

// ErrorResponse - Any bad or invalid request will lead to following error object
type ErrorResponse struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// One of ["invalid_request_error", "authentication_error", "rate_limit_error", "validation_error", "api_error"]
	Type *ErrorResponseType `json:"type,omitempty"`
}

func (o *ErrorResponse) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *ErrorResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *ErrorResponse) GetType() *ErrorResponseType {
	if o == nil {
		return nil
	}
	return o.Type
}
