// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OrderMeta struct {
	// Notification URL for server-server communication. Useful when user's connection drops while re-directing. NotifyUrl should be an https URL. Maximum length: 250.
	NotifyURL *string `json:"notify_url,omitempty"`
	// Allowed payment modes for this order. Pass comma-separated values among following options - "cc", "dc", "ccc", "ppc","nb","upi","paypal","app","paylater","cardlessemi","dcemi","ccemi","banktransfer". Leave it blank to show all available payment methods
	PaymentMethods *string `json:"payment_methods,omitempty"`
	// The URL to which user will be redirected to after the payment on bank OTP page. Maximum length: 250. The return_url must contain placeholder {order_id}. When redirecting the customer back to the return url from the bank’s OTP page, Cashfree will replace this placeholder with the actual value for that order.
	ReturnURL *string `json:"return_url,omitempty"`
}

func (o *OrderMeta) GetNotifyURL() *string {
	if o == nil {
		return nil
	}
	return o.NotifyURL
}

func (o *OrderMeta) GetPaymentMethods() *string {
	if o == nil {
		return nil
	}
	return o.PaymentMethods
}

func (o *OrderMeta) GetReturnURL() *string {
	if o == nil {
		return nil
	}
	return o.ReturnURL
}
