// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OrdersEntity struct {
	CfOrderID *int64 `json:"cf_order_id,omitempty"`
	// The customer details that are necessary. Note that you can pass dummy details if your use case does not require the customer details.
	CustomerDetails  *CustomerDetails     `json:"customer_details,omitempty"`
	Entity           *string              `json:"entity,omitempty"`
	OrderAmount      *float64             `json:"order_amount,omitempty"`
	OrderCurrency    *string              `json:"order_currency,omitempty"`
	OrderExpiryTime  *string              `json:"order_expiry_time,omitempty"`
	OrderID          *string              `json:"order_id,omitempty"`
	OrderMeta        *OrderMeta           `json:"order_meta,omitempty"`
	OrderNote        *string              `json:"order_note,omitempty"`
	OrderStatus      *string              `json:"order_status,omitempty"`
	PaymentSessionID *string              `json:"payment_session_id,omitempty"`
	Payments         *PaymentURLObject    `json:"payments,omitempty"`
	Refunds          *RefundURLObject     `json:"refunds,omitempty"`
	Settlements      *SettlementURLObject `json:"settlements,omitempty"`
}

func (o *OrdersEntity) GetCfOrderID() *int64 {
	if o == nil {
		return nil
	}
	return o.CfOrderID
}

func (o *OrdersEntity) GetCustomerDetails() *CustomerDetails {
	if o == nil {
		return nil
	}
	return o.CustomerDetails
}

func (o *OrdersEntity) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *OrdersEntity) GetOrderAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.OrderAmount
}

func (o *OrdersEntity) GetOrderCurrency() *string {
	if o == nil {
		return nil
	}
	return o.OrderCurrency
}

func (o *OrdersEntity) GetOrderExpiryTime() *string {
	if o == nil {
		return nil
	}
	return o.OrderExpiryTime
}

func (o *OrdersEntity) GetOrderID() *string {
	if o == nil {
		return nil
	}
	return o.OrderID
}

func (o *OrdersEntity) GetOrderMeta() *OrderMeta {
	if o == nil {
		return nil
	}
	return o.OrderMeta
}

func (o *OrdersEntity) GetOrderNote() *string {
	if o == nil {
		return nil
	}
	return o.OrderNote
}

func (o *OrdersEntity) GetOrderStatus() *string {
	if o == nil {
		return nil
	}
	return o.OrderStatus
}

func (o *OrdersEntity) GetPaymentSessionID() *string {
	if o == nil {
		return nil
	}
	return o.PaymentSessionID
}

func (o *OrdersEntity) GetPayments() *PaymentURLObject {
	if o == nil {
		return nil
	}
	return o.Payments
}

func (o *OrdersEntity) GetRefunds() *RefundURLObject {
	if o == nil {
		return nil
	}
	return o.Refunds
}

func (o *OrdersEntity) GetSettlements() *SettlementURLObject {
	if o == nil {
		return nil
	}
	return o.Settlements
}
