// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaymentSuccessWebhook struct {
	Data      *WHdata `json:"data,omitempty"`
	EventTime *string `json:"event_time,omitempty"`
	Type      *string `json:"type,omitempty"`
}

func (o *PaymentSuccessWebhook) GetData() *WHdata {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *PaymentSuccessWebhook) GetEventTime() *string {
	if o == nil {
		return nil
	}
	return o.EventTime
}

func (o *PaymentSuccessWebhook) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
