// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// RateLimitErrorType - rate_limit_error
type RateLimitErrorType string

const (
	RateLimitErrorTypeRateLimitError RateLimitErrorType = "rate_limit_error"
)

func (e RateLimitErrorType) ToPointer() *RateLimitErrorType {
	return &e
}

func (e *RateLimitErrorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "rate_limit_error":
		*e = RateLimitErrorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RateLimitErrorType: %v", v)
	}
}
