// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TerminalDetails struct {
	// The internal id that you use to map the terminal in your internal system
	TerminalID string `json:"terminal_id"`
	// Phone no assigned to the terminal
	TerminalPhoneNo string `json:"terminal_phone_no"`
	// To identify the type of terminal product in use, in this case it is SPOS
	TerminalType string `json:"terminal_type"`
}

func (o *TerminalDetails) GetTerminalID() string {
	if o == nil {
		return ""
	}
	return o.TerminalID
}

func (o *TerminalDetails) GetTerminalPhoneNo() string {
	if o == nil {
		return ""
	}
	return o.TerminalPhoneNo
}

func (o *TerminalDetails) GetTerminalType() string {
	if o == nil {
		return ""
	}
	return o.TerminalType
}
