// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type VendorSplit struct {
	// Amount which will be associated with this vendor
	Amount *float64 `json:"amount,omitempty"`
	// Percentage of order amount which shall get added to vendor account
	Percentage *float64 `json:"percentage,omitempty"`
	// Vendor id created in Cashfree system
	VendorID *string `json:"vendor_id,omitempty"`
}

func (o *VendorSplit) GetAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *VendorSplit) GetPercentage() *float64 {
	if o == nil {
		return nil
	}
	return o.Percentage
}

func (o *VendorSplit) GetVendorID() *string {
	if o == nil {
		return nil
	}
	return o.VendorID
}
