// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WHcard struct {
	CardBankName *string `json:"card_bank_name,omitempty"`
	CardCounty   *string `json:"card_county,omitempty"`
	CardNetwork  *string `json:"card_network,omitempty"`
	CardNumber   *string `json:"card_number,omitempty"`
	CardType     *string `json:"card_type,omitempty"`
	Channel      *string `json:"channel,omitempty"`
}

func (o *WHcard) GetCardBankName() *string {
	if o == nil {
		return nil
	}
	return o.CardBankName
}

func (o *WHcard) GetCardCounty() *string {
	if o == nil {
		return nil
	}
	return o.CardCounty
}

func (o *WHcard) GetCardNetwork() *string {
	if o == nil {
		return nil
	}
	return o.CardNetwork
}

func (o *WHcard) GetCardNumber() *string {
	if o == nil {
		return nil
	}
	return o.CardNumber
}

func (o *WHcard) GetCardType() *string {
	if o == nil {
		return nil
	}
	return o.CardType
}

func (o *WHcard) GetChannel() *string {
	if o == nil {
		return nil
	}
	return o.Channel
}
