// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WHdata struct {
	CustomerDetails *WHcustomerDetails `json:"customer_details,omitempty"`
	Order           *WHorder           `json:"order,omitempty"`
	Payment         *WHpayment         `json:"payment,omitempty"`
}

func (o *WHdata) GetCustomerDetails() *WHcustomerDetails {
	if o == nil {
		return nil
	}
	return o.CustomerDetails
}

func (o *WHdata) GetOrder() *WHorder {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *WHdata) GetPayment() *WHpayment {
	if o == nil {
		return nil
	}
	return o.Payment
}
