// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WHorder struct {
	OrderAmount   *float64 `json:"order_amount,omitempty"`
	OrderCurrency *string  `json:"order_currency,omitempty"`
	OrderID       *string  `json:"order_id,omitempty"`
	OrderTags     *string  `json:"order_tags,omitempty"`
}

func (o *WHorder) GetOrderAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.OrderAmount
}

func (o *WHorder) GetOrderCurrency() *string {
	if o == nil {
		return nil
	}
	return o.OrderCurrency
}

func (o *WHorder) GetOrderID() *string {
	if o == nil {
		return nil
	}
	return o.OrderID
}

func (o *WHorder) GetOrderTags() *string {
	if o == nil {
		return nil
	}
	return o.OrderTags
}
