// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WHpaymentMethod struct {
	Card *WHcard `json:"card,omitempty"`
}

func (o *WHpaymentMethod) GetCard() *WHcard {
	if o == nil {
		return nil
	}
	return o.Card
}
